import { createContext, useContext, useState, useEffect } from 'react';

// Admin-panel UI strings. The customer-facing menu uses a separate table
// (src/i18n.js); this one only covers the /admin chrome. Russian is the
// default; English is kept as a switchable fallback.
export const adminStrings = {
  ru: {
    // login
    panel: 'Админ-панель',
    password: 'Пароль',
    wrongPassword: 'Неверный пароль',
    signIn: 'Войти',
    // header
    admin: 'Админ',
    viewMenu: 'Открыть меню',
    logout: 'Выйти',
    // tabs
    tabDishes: '☕ Напитки',
    tabCategories: '🏷 Категории',
    tabPromotions: '🔥 Акции',
    tabOrders: '🧾 Заказы',
    tabSettings: '⚙️ Настройки',
    tabQr: '🔳 QR',
    // common
    new: '+ Создать',
    edit: 'Изменить',
    del: 'Удал.',
    cancel: 'Отмена',
    save: 'Сохранить',
    saved: '✓ Сохранено',
    loading: 'Загрузка…',
    editTitle: 'Изменить',
    newTitle: 'Создать',
    // dishes
    drinks: 'Напитки',
    drink: 'напиток',
    confirmDeleteDrink: 'Удалить этот напиток?',
    hidden: 'скрыт',
    name: 'Название',
    description: 'Описание',
    ingredients: 'Ингредиенты (через запятую, по языкам)',
    priceAzn: 'Цена (AZN)',
    category: 'Категория',
    calories: 'Калории',
    weight: 'Вес (мл/г)',
    sizesOptional: 'Размеры (необязательно)',
    addSize: '+ Размер',
    noSizes: 'Без размеров — используется одна цена выше. Добавьте, например, S / M для коктейлей.',
    sizeLabelPh: 'Метка (S, M…)',
    sizeTip: 'Совет: держите поле «Цена (AZN)» равным наименьшему размеру — оно показывается на карточках и как запасное значение.',
    featured: 'Рекомендуемое ★',
    available: 'Доступно',
    photoOptional: 'Фото (необязательно)',
    removePhoto: 'Удалить фото',
    // categories
    categories: 'Категории',
    categoryWord: 'категория',
    confirmDeleteCategory: 'Удалить категорию?',
    sortOrder: 'Порядок',
    icon: 'Иконка',
    iconBuiltIn: 'Встроенная',
    iconCustom: 'Своя',
    uploadIcon: 'Загрузить иконку',
    // promotions
    promotions: 'Акции',
    promotionWord: 'акция',
    confirmDeletePromotion: 'Удалить акцию?',
    title: 'Заголовок',
    discount: 'Скидка %',
    // orders
    orders: 'Заказы',
    noOrders: 'Заказов пока нет.',
    fromQr: 'Из QR-кода',
    statusNew: 'Новый',
    statusPreparing: 'Готовится',
    statusReady: 'Готов',
    statusDone: 'Выдан',
    statusCancelled: 'Отменён',
    // settings
    settings: 'Настройки',
    cafeName: 'Название кофейни',
    phone: 'Телефон',
    instagram: 'Instagram',
    wifiName: 'Имя Wi-Fi',
    wifiPassword: 'Пароль Wi-Fi',
    address: 'Адрес',
    accentColor: 'Акцентный цвет',
    menuUrl: 'URL меню (для QR)',
    newAdminPassword: 'Новый пароль администратора',
    leaveBlank: 'оставьте пустым',
    whatsappFixed: 'Номер WhatsApp фиксирован:',
    saveSettings: 'Сохранить настройки',
    // qr
    qrCode: 'QR-код',
    tableNumber: 'Номер стола (необязательно)',
    generate: 'Сгенерировать',
    download: 'Скачать',
  },
  en: {
    panel: 'Admin Panel',
    password: 'Password',
    wrongPassword: 'Wrong password',
    signIn: 'Sign in',
    admin: 'Admin',
    viewMenu: 'View menu',
    logout: 'Logout',
    tabDishes: '☕ Dishes',
    tabCategories: '🏷 Categories',
    tabPromotions: '🔥 Promotions',
    tabOrders: '🧾 Orders',
    tabSettings: '⚙️ Settings',
    tabQr: '🔳 QR',
    new: '+ New',
    edit: 'Edit',
    del: 'Del',
    cancel: 'Cancel',
    save: 'Save',
    saved: '✓ Saved',
    loading: 'Loading…',
    editTitle: 'Edit',
    newTitle: 'New',
    drinks: 'Drinks',
    drink: 'drink',
    confirmDeleteDrink: 'Delete this drink?',
    hidden: 'hidden',
    name: 'Name',
    description: 'Description',
    ingredients: 'Ingredients (comma list per lang)',
    priceAzn: 'Price (AZN)',
    category: 'Category',
    calories: 'Calories',
    weight: 'Weight (ml/g)',
    sizesOptional: 'Sizes (optional)',
    addSize: '+ Add size',
    noSizes: 'No sizes — the single price above is used. Add e.g. S / M for milkshakes.',
    sizeLabelPh: 'Label (S, M…)',
    sizeTip: 'Tip: keep the “Price (AZN)” field equal to the smallest size — it’s shown on cards and used as a fallback.',
    featured: 'Featured ★',
    available: 'Available',
    photoOptional: 'Photo (optional)',
    removePhoto: 'Remove photo',
    categories: 'Categories',
    categoryWord: 'category',
    confirmDeleteCategory: 'Delete category?',
    sortOrder: 'Sort order',
    icon: 'Icon',
    iconBuiltIn: 'Built-in',
    iconCustom: 'Custom',
    uploadIcon: 'Upload icon',
    promotions: 'Promotions',
    promotionWord: 'promotion',
    confirmDeletePromotion: 'Delete promotion?',
    title: 'Title',
    discount: 'Discount %',
    orders: 'Orders',
    noOrders: 'No orders yet.',
    fromQr: 'From QR code',
    statusNew: 'New',
    statusPreparing: 'Preparing',
    statusReady: 'Ready',
    statusDone: 'Done',
    statusCancelled: 'Cancelled',
    settings: 'Settings',
    cafeName: 'Café name',
    phone: 'Phone',
    instagram: 'Instagram',
    wifiName: 'Wi-Fi name',
    wifiPassword: 'Wi-Fi password',
    address: 'Address',
    accentColor: 'Accent color',
    menuUrl: 'Menu URL (for QR)',
    newAdminPassword: 'New admin password',
    leaveBlank: 'leave blank to keep',
    whatsappFixed: 'WhatsApp number is fixed:',
    saveSettings: 'Save settings',
    qrCode: 'QR Code',
    tableNumber: 'Table number (optional)',
    generate: 'Generate',
    download: 'Download',
  },
};

const AdminLangContext = createContext({ lang: 'ru', setLang: () => {}, t: adminStrings.ru });

export function AdminLangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('admin_lang') || 'ru');
  useEffect(() => { localStorage.setItem('admin_lang', lang); }, [lang]);
  const value = { lang, setLang, t: adminStrings[lang] || adminStrings.ru };
  return <AdminLangContext.Provider value={value}>{children}</AdminLangContext.Provider>;
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
